max_width = 80
ideal_width = 80
tab_spaces = 2
fn_args_density = "Compressed"
fn_call_width = 78
fn_single_line = true
reorder_imports = true
reorder_imported_names = true
single_line_if_else_max_width = 78
# space_before_bound = true
# space_before_type_annotation = true
struct_lit_width = 78
