[package]
name = "textbox"
version = "0.0.1"
authors = ["Matthew O'Connor <thegreendragon@gmail.com>"]

[dependencies]
bitflags = "*"
bit-set = "*"
num-traits = "*"

[target.'cfg(windows)'.dependencies]
winapi = { path = "../../winapi-rs" }
wio = { path = "../../wio-rs" }
kernel32-sys = "*"

[target.'cfg(unix)'.dependencies]
termbox-sys = "*"
